analytics: {}
color:
  brandColors:
    - '#A19271'
    - '#C6BD00'
    - '#1C2021'
    - '#961A4E'
    - '#484D47'
  brandStrength: 0.324324
  lightness: 0.478041
  rhythmicContrast: 0.769426
  saturation: 0.73902
cta: {}
layout_spectrum: 0.475507
name: Kaleidoscope
opengraph: {}
purpose: []
typography_spectrum: 0.307432
