analytics: {}
color:
  brandColors:
    - '#383025'
    - '#8AA7B9'
    - '#BFD7D9'
    - '#000600'
    - '#FEFEFE'
  brandStrength: 0
  lightness: 0.724662
  rhythmicContrast: 0.254223
  saturation: 0.245777
cta: {}
layout_spectrum: 0.50308
name: Kaleidoscope
opengraph: {}
purpose: []
typography_spectrum: 0.063345
