name: Kaleidoscope
favicon: null
layout_spectrum: 0.4518254071008414
typography_spectrum: 0.23159984149970114
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8344480583909899
  lightness: 0.05547133646905422
  saturation: 0.27611567778512836
  rhythmicContrast: 0.23868369543924928
purpose: []
