name: Kaleidoscope
favicon: null
layout_spectrum: 0.94007
typography_spectrum: 0.88316
title: Kaleidoscope
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010010'
    - '#fefefe'
    - '#a1ad81'
    - '#e1442a'
    - '#334c57'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
